quest Iyilestirme5LvBec begin
	state start begin
		when login begin
			cmdchat("iyilestirme_oto_bec "..q.getcurrentquestindex())
		end
		when info or button begin
		local pc_job = pc . get_job ( ) 
		if pc_job ~= 3 then 
		--say_title ( "Yanlýþ Eðitim " ) 
		--say ( "" ) 
		--say ( "Özür Dilerim." ) 
		--say ( "Sadece samanlar Ejderha Gücü eðitimini" ) 
		--say ( "seçebilir." ) 
		--say ( "" ) 
		if pc_job == 0 then 
		--say_reward ( "Bir Savaþçý, Zihinsel Savaþý " ) 
		--say_reward ( "veya Bedensel Savaþý " ) 
		--say_reward ( "seçebilir." ) 
		elseif pc_job == 1 then 
		--say_reward ( "Bir Ninja, Yakin Dövüþ veya" ) 
		--say_reward ( "Uzak Dövüþ eðitimini" ) 
		--say_reward ( "seçebilir." ) 
		elseif pc_job == 2 then 
		--say_reward ( "Bir Sura, Büyülü Silah" ) 
		--say_reward ( "veya Kara Büyü eðitimini" ) 
		--say_reward ( "seçebilir." ) 
		elseif pc_job == 3 then 
		--say_reward ( "Bir saman, Ejderha Gücü eðitimini" ) 
		--say_reward ( "veya iyilestirme eðitimini" ) 
		--say_reward ( "seçebilir." ) 
		end 
		--say ( "" ) 
		return 
		end 
		--say_title ( "Ejderha Gücü eðitimi" ) 
		--say ( "" ) 
		--say ( "Ejderha Gücü eðitiminde, Ejderha Tanrýnýn " ) 
		--say ( "güçlü ateþ saldýrýlarýný yönetmeyi ve " ) 
		--say ( "dayanýklýlýk büyüleriyle Ejderha Tanrýnýn " ) 
		--say ( "korumasýný kullanmayi ögrenirler." ) 
		--say_reward ( "Gereksinim: Seviye 5 ve üstü bir savaþçý olmak" ) 
		--say ( "" ) 
		--local s = select ( "Baþla" , "Daha sonra" ) 
		if 2 == s then 
		return 
		end 
		if pc . get_job ( ) ~= 3 or pc . get_skill_group ( ) ~= 0 then 
		test_chat ( "npc_is_same_job:" .. bool_to_str ( npc_is_same_job ( ) ) ) 
		test_chat ( "pc.get_skill_group:" .. pc . get_skill_group ( ) ) 
		test_chat ( "pc_job:" .. pc . get_job ( ) ) 
		return 
		end 
		--set_state ( "start" ) 
		pc . set_skill_group ( 1 ) 
		pc . clear_skill ( ) 
		char_log ( 0 , "CLEAR_SKILL" , "Ögretmen silindikten sonraki dogal yetenek." ) 
		--say_title ( "Ejderha Gücü eðitimini seçtin." ) 
--		say ( "Hoþgeldin!" ) 
		if not pc . is_clear_skill_group ( ) then 
		--say ( "Ders almayý seçtiðin için 4 yetenek puaný " ) 
		--say ( "kazandýn. Bu puanlarý dilediðin herhangi bir" ) 
		--say ( "yeteneðini geliþtirmek için kullabilirsin." ) 
		--say_title ( "Bilgi:" ) 
		--say_reward ( "4 yetenek puaný kazandýn." ) 
		--say ( "" ) 
		pc . set_skill_level ( 91 , 30 )
		pc . set_skill_level ( 92 , 30 )
		pc . set_skill_level ( 93 , 30 )
		pc . set_skill_level ( 94 , 30 )
		pc . set_skill_level ( 95 , 30 )
		pc . set_skill_level ( 96 , 30 )
		pc . set_skill_level ( 137 , 30 )
		pc . set_skill_level ( 138 , 30 )
		pc . set_skill_level ( 139 , 30 )
		pc . set_skill_level ( 131 , 10 ) 
		pc . set_skill_level ( 129 , 40 ) 
		pc . set_skill_level ( 128 , 30 )
		pc . set_skill_level ( 127 , 30 )
		pc . set_skill_level ( 126 , 30 )
		pc . set_skill_level ( 124 , 40 ) 
		pc . set_skill_level ( 121 , 40 ) 
		pc . set_skill_level ( 122 , 2 )
		pc.set_skill_level (137,59)
		pc.set_skill_level (138,59)
		pc.set_skill_level (139,59)
		pc.set_skill_level (140,59)
		pc.set_skill_level (124,59)
		pc.set_skill_level (131,59)
		pc.set_skill_level (121,59)
		pc.set_skill_level (122,59)
		pc.set_skill_level (129,59)
		pc.set_skill_level (126,59)
		pc.set_skill_level (127,59)
		pc.set_skill_level (128,59)
		pc.set_skill_level (130,59)
		horse . unride ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( )
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( ) 
		horse . advance ( )  
		else 
		--say_reward ( "Yeni bir ders seçtiginde," ) 
		--say_reward ( "daha fazla tecrübe puani almayacaksin." ) 
		--say ( "" ) 
		end 
		clear_letter ( )
		end
	end
end